name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
      - name: Run Tests
        run: |
          source devel/setup.bash
          rostest suitcase test.launch
        working-directory: ../suitcase/